import type { Interaction, Lead, Owner, SalesCostPeriod } from "@/lib/types";

export const owners: Owner[] = [
  { id: "owner-ife", name: "Ife" },
  { id: "owner-zainab", name: "Zainab" },
  { id: "owner-chidi", name: "Chidi" }
];

export const seedLeads: Lead[] = [
  {
    id: "lead-kobo-mart",
    name: "Adaora Nwosu",
    company: "KoboMart Wholesale",
    phone: "+234 803 441 1190",
    email: "adaora@kobomart.ng",
    stage: "proposal_sent",
    temperature: "hot",
    source: "Referral",
    referrerName: "Tunde B.",
    relationshipStrength: "strong",
    ownerId: "owner-ife",
    dealValue: 4800000,
    probability: 65,
    nextAction: "",
    nextActionDate: "",
    lastTouchDate: "2026-04-28",
    createdAt: "2026-04-09",
    updatedAt: "2026-04-28",
    statusReason: "Waiting for finance approval after warehouse demo.",
    tags: ["wholesale", "lagos", "inventory"],
    notes: "Interested in stock alerts and sales rep tracking across Alaba and Trade Fair routes."
  },
  {
    id: "lead-medplus",
    name: "Dr. Seyi Aluko",
    company: "Medplus Clinics Abuja",
    phone: "+234 802 773 2218",
    email: "seyi@medplusclinics.ng",
    stage: "meeting_demo",
    temperature: "warm",
    source: "LinkedIn",
    referrerName: "",
    relationshipStrength: "medium",
    ownerId: "owner-zainab",
    dealValue: 6200000,
    probability: 45,
    nextAction: "Confirm Thursday demo attendees on WhatsApp",
    nextActionDate: "2026-05-03",
    lastTouchDate: "2026-05-01",
    createdAt: "2026-04-19",
    updatedAt: "2026-05-01",
    statusReason: "Ops lead asked to see patient follow-up workflow.",
    tags: ["healthcare", "abuja", "demo"],
    notes: "Needs simple reporting for branch managers."
  },
  {
    id: "lead-bluegate",
    name: "Emeka Okafor",
    company: "Bluegate Logistics",
    phone: "+234 701 554 9090",
    email: "emeka@bluegatelogistics.com",
    stage: "talking",
    temperature: "hot",
    source: "WhatsApp community",
    referrerName: "Nkechi from FleetOps",
    relationshipStrength: "strong",
    ownerId: "owner-chidi",
    dealValue: 3500000,
    probability: 40,
    nextAction: "Send voice note recap and ask for depot visit slot",
    nextActionDate: "2026-05-02",
    lastTouchDate: "2026-04-29",
    createdAt: "2026-04-24",
    updatedAt: "2026-04-29",
    statusReason: "Owner wants proof that drivers can update jobs by phone.",
    tags: ["logistics", "port-harcourt"],
    notes: "Potential multi-city rollout if depot pilot works."
  },
  {
    id: "lead-sunrise",
    name: "Fatima Bello",
    company: "Sunrise Foods Kano",
    phone: "+234 809 020 7788",
    email: "fatima@sunrisefoods.ng",
    stage: "new",
    temperature: "hot",
    source: "Trade fair",
    referrerName: "",
    relationshipStrength: "medium",
    ownerId: "owner-zainab",
    dealValue: 2800000,
    probability: 25,
    nextAction: "",
    nextActionDate: "",
    lastTouchDate: "2026-05-02",
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    statusReason: "Asked for distributor price list automation.",
    tags: ["fmcg", "kano", "hot"],
    notes: "Prefers WhatsApp messages before calls."
  },
  {
    id: "lead-ajala",
    name: "Bamidele Ajala",
    company: "Ajala & Sons Building Materials",
    phone: "+234 805 998 3360",
    email: "bamidele@ajalasupplies.ng",
    stage: "talking",
    temperature: "warm",
    source: "Existing customer intro",
    referrerName: "Musa from SiteTrack",
    relationshipStrength: "strong",
    ownerId: "owner-ife",
    dealValue: 2200000,
    probability: 35,
    nextAction: "Call procurement manager after morning delivery run",
    nextActionDate: "2026-05-03",
    lastTouchDate: "2026-04-26",
    createdAt: "2026-04-15",
    updatedAt: "2026-04-26",
    statusReason: "Needs approval from brother who handles accounts.",
    tags: ["construction", "ibadan"],
    notes: "Strong referral. Keep WhatsApp updates short."
  },
  {
    id: "lead-orchid",
    name: "Morenike Thomas",
    company: "Orchid Schools Lekki",
    phone: "+234 813 112 4455",
    email: "morenike@orchidschools.edu.ng",
    stage: "proposal_sent",
    temperature: "warm",
    source: "Web enquiry",
    referrerName: "",
    relationshipStrength: "weak",
    ownerId: "owner-chidi",
    dealValue: 1800000,
    probability: 55,
    nextAction: "Follow up with bursar on payment timeline",
    nextActionDate: "2026-05-04",
    lastTouchDate: "2026-04-30",
    createdAt: "2026-04-16",
    updatedAt: "2026-04-30",
    statusReason: "Proposal shared for parent communication tool.",
    tags: ["education", "lekki"],
    notes: "Bursar asked about annual discount."
  },
  {
    id: "lead-northstar",
    name: "Hassan Garba",
    company: "Northstar Agro Inputs",
    phone: "+234 806 707 1212",
    email: "hassan@northstaragro.ng",
    stage: "talking",
    temperature: "cold",
    source: "Cold outbound",
    referrerName: "",
    relationshipStrength: "weak",
    ownerId: "owner-zainab",
    dealValue: 1200000,
    probability: 15,
    nextAction: "Share one-page WhatsApp ordering example",
    nextActionDate: "2026-05-06",
    lastTouchDate: "2026-04-24",
    createdAt: "2026-04-12",
    updatedAt: "2026-04-24",
    statusReason: "Interested but not urgent until next planting cycle.",
    tags: ["agro", "kaduna"],
    notes: "May become relevant in June."
  },
  {
    id: "lead-easyhaul",
    name: "Uche Eze",
    company: "EasyHaul Dispatch",
    phone: "+234 704 889 4545",
    email: "uche@easyhaul.co",
    stage: "won",
    temperature: "hot",
    source: "Partner",
    referrerName: "Lola at PayRail",
    relationshipStrength: "strong",
    ownerId: "owner-ife",
    dealValue: 3000000,
    probability: 100,
    nextAction: "Schedule onboarding checklist review",
    nextActionDate: "2026-05-07",
    lastTouchDate: "2026-05-01",
    createdAt: "2026-03-28",
    updatedAt: "2026-05-01",
    statusReason: "Paid first annual invoice.",
    tags: ["dispatch", "won"],
    notes: "Good candidate for testimonial after onboarding."
  }
];

export const seedInteractions: Interaction[] = [
  {
    id: "int-1",
    leadId: "lead-kobo-mart",
    type: "proposal_sent",
    summary: "Shared proposal for warehouse stock and sales route workflow.",
    nextAction: "",
    nextActionDate: "",
    createdAt: "2026-04-28T14:20:00.000Z",
    ownerId: "owner-ife"
  },
  {
    id: "int-2",
    leadId: "lead-medplus",
    type: "whatsapp",
    summary: "Dr. Seyi confirmed interest and asked to include operations lead in demo.",
    nextAction: "Confirm Thursday demo attendees on WhatsApp",
    nextActionDate: "2026-05-03",
    createdAt: "2026-05-01T10:05:00.000Z",
    ownerId: "owner-zainab"
  },
  {
    id: "int-3",
    leadId: "lead-bluegate",
    type: "call",
    summary: "Discussed depot visibility and driver updates for delivery jobs.",
    nextAction: "Send voice note recap and ask for depot visit slot",
    nextActionDate: "2026-05-02",
    createdAt: "2026-04-29T16:40:00.000Z",
    ownerId: "owner-chidi"
  },
  {
    id: "int-4",
    leadId: "lead-easyhaul",
    type: "payment",
    summary: "Payment confirmed for annual dispatch operations package.",
    nextAction: "Schedule onboarding checklist review",
    nextActionDate: "2026-05-07",
    createdAt: "2026-05-01T13:15:00.000Z",
    ownerId: "owner-ife"
  }
];

export const seedCostPeriod: SalesCostPeriod = {
  id: "cost-may-2026",
  label: "May 2026 plan",
  startDate: "2026-05-01",
  endDate: "2026-05-31",
  salesCost: 2400000,
  marketingCost: 900000,
  targetCustomers: 18,
  averageMonthlyGrossProfitPerCustomer: 180000
};
